name: Trigger Cloudflare Deploy

on:
  workflow_run:
    workflows: ["Update Stock Tracker"]
    types:
      - completed
  workflow_dispatch:

jobs:
  trigger-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Cloudflare Pages Deploy Hook
        run: |
          # Option 1: Using Cloudflare Deploy Hook (if configured)
          # curl -X POST "${{ secrets.CLOUDFLARE_DEPLOY_HOOK_URL }}"

          # Option 2: Using Cloudflare API
          # Requires CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID secrets
          # curl -X POST "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/YOUR_PROJECT_NAME/deployments" \
          #   -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          #   -H "Content-Type: application/json"

          echo "Deploy triggered for latest commit"